### ISSUE TITLE
Request for full OPML of Cyber Security podcasts

### ISSUE THREAD

**Issue by CleverClogs** [Blake-/cyber-security-podcasts#3]
Hi Blake-,
What a fantastic collection of Cyber Security podcasts you built. Have you subscribed to these in an RSS reader? If so, would you mind publishing the full OPML? The OPML currently available from your folder unfortunately is incomplete.

I'd like to subscribe to your OPML using Inoreader. It has the advantage that when you update the OPML, Inoreader will detect it and notify me. 
Thank you very much.

**Comment by Blake-** [comment]
Hi @CleverClogs 
No, sorry, I've yet to make a real, full, functioning OPML for the list. I'm hoping to get there!

**Comment by Blake-** [comment]
All set!

https://github.com/Blake-/cyber-security-podcasts/blob/main/cyber-security-podcasts.opml

**Comment by CleverClogs** [comment]
Fantastic, Blake. I so appreciate this. I've immediately added your OPML file as a new OPML subscription to Inoreader and it has neatly added 88 podcast feeds. When you add a new feed to the OPML, Inoreader will automatically register the change and add the new feed to the collection. 

Here's a screenshot of the new folder I created for the your podcast collection:
![image](https://user-images.githubusercontent.com/2105606/191112006-83d9fe7c-51e9-4806-bccb-f93700695245.png)

Please reach out if you'd like to demo it to you. Thank you so much!
